[FIX] 회원관련 코드 수정 / 팔로우 기능 / 선수 개인정보 검색 기능 구현
BBIKKIBBIKKI/final-project pull request #15
Opened 2024-10-25 02:43 UTC by leejaehee0807

1. 회원 관련코드 불필요한 부분 삭제
2. 선수 단건 조회 기능 생성
3. 팔로우 기능 추가

2024-10-25 11:29 UTC, ekj1003 requested changes

2024-10-25 11:29 UTC, ekj1003 commented on src/main/java/com/wearei/finalsamplecode/domain/auth/service/AuthService.java
띄어쓰기 지워주세용

2024-10-25 11:29 UTC, ekj1003 commented on src/main/java/com/wearei/finalsamplecode/domain/follow/entity/Follow.java
> +
띄어쓰기 삭제해주세용

2024-10-25 11:29 UTC, ekj1003 commented on src/main/java/com/wearei/finalsamplecode/domain/player/entity/Player.java
> +
띄어쓰기 삭제해주세용

2024-10-25 11:29 UTC, ekj1003 commented on src/main/java/com/wearei/finalsamplecode/domain/user/entity/User.java
띄어쓰기 삭제해주세용

2024-10-25 11:29 UTC, ekj1003 commented on src/main/java/com/wearei/finalsamplecode/domain/user/service/UserService.java
띄어쓰기 삭제해주세용

2024-10-28 01:16 UTC, HyunKook-Park approved these changes

2024-10-28 01:17 UTC, jeunwoosung approved these changes

2024-10-28 01:58 UTC, duduio2050 reviewed
수정부탁드립니다.

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/auth/controller/AuthController.java
> +            @RequestBody SignupRequest signupRequest){
이거 이전 것이 더 보기 좋은 것 같아요

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/player/entity/Player.java
> +    private Long playerAge;
너무 붙어 있어서 읽기 너무 힘든 것 같아요

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/user/dto/request/UserDeleteRequest.java
> +public class UserDeleteRequest{
UserDeleteRequest { 

스페이스바 넣으면 좋겠습니다.

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/user/dto/request/UserUpdateRequest.java
> +public class UserUpdateRequest{
스페이스바 넣으면 좋겠습니다.

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/auth/dto/request/SigninRequest.java
> +public class SigninRequest{
스페이스바

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/auth/controller/AuthController.java
> +            @RequestBody SigninRequest signinRequest){
스페이스바

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/auth/dto/request/SignupRequest.java
> +public class SignupRequest{
스페이스바

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/auth/dto/response/SigninResponse.java
> +public class SigninResponse{
스페이스바

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/auth/dto/response/SignupResponse.java
> +public class SignupResponse{
스페이스바

2024-10-28 01:58 UTC, duduio2050 commented on src/main/java/com/wearei/finalsamplecode/domain/auth/service/AuthService.java
> +public class AuthService{
스페이스바

2024-10-28 02:13 UTC, ekj1003 approved these changes

2024-10-28 02:24 UTC, duduio2050 approved these changes

2024-10-28 02:24 UTC, merged

2024-10-28 05:25 UTC, minahshin commented on src/main/java/com/wearei/finalsamplecode/domain/auth/dto/request/SigninRequest.java
>  @AllArgsConstructor
필요 없는 AllArgsConstructor은 두실 필요 없습니다!
또한, AllArgsConstructor보다는 직접 선언하시는 것이 좋습니다!
아래 내용에서 빌더 패턴 내용을 제외하고 참조해주세요! (빌더 패턴은 철호 튜터님께서 코멘트 주신 것을 참고해주시면 됩니다.)
ref) https://techjisu.tistory.com/155