[FIX] 어노테이션, Build 관련 피드백 반영
BBIKKIBBIKKI/final-project pull request #23
Opened 2024-10-28 08:44 UTC by HyunKook-Park

2024-10-28 08:46 UTC, jeunwoosung requested changes

2024-10-28 08:46 UTC, jeunwoosung commented on src/test/java/com/wearei/finalsamplecode/domain/menu/service/MenuServiceTest.java
> +
엔터처리 수정부탁드립니당

2024-10-28 08:46 UTC, leejaehee0807 commented on src/main/java/com/wearei/finalsamplecode/domain/store/dto/request/StoreCreateRequest.java
17번줄 줄 없애주시면 감사하겠습니다.

2024-10-28 08:46 UTC, leejaehee0807 commented on src/test/java/com/wearei/finalsamplecode/domain/menu/service/MenuServiceTest.java
4번줄 지워주시면 감사하겠습니다.

2024-10-28 08:46 UTC, leejaehee0807 commented on src/test/java/com/wearei/finalsamplecode/domain/store/service/StoreServiceTest.java
29번줄 붙여주시면 감사하겠습니다

2024-10-28 08:50 UTC, duduio2050 commented on src/test/java/com/wearei/finalsamplecode/domain/store/service/StoreServiceTest.java
> +    @Test
사용하지 않는 코드 삭제 부탁드립니다.

2024-10-28 08:55 UTC, ekj1003 approved these changes
좋습니당!

2024-10-28 08:55 UTC, HyunKook-Park commented on src/test/java/com/wearei/finalsamplecode/domain/menu/service/MenuServiceTest.java
> +
반영 완료

2024-10-28 08:56 UTC, HyunKook-Park commented on src/test/java/com/wearei/finalsamplecode/domain/menu/service/MenuServiceTest.java
반영 완료

2024-10-28 08:56 UTC, HyunKook-Park commented on src/test/java/com/wearei/finalsamplecode/domain/store/service/StoreServiceTest.java
반영 완료

2024-10-28 08:56 UTC, HyunKook-Park commented on src/main/java/com/wearei/finalsamplecode/domain/store/dto/request/StoreCreateRequest.java
> +
반영 완료

2024-10-28 08:56 UTC, HyunKook-Park commented on src/main/java/com/wearei/finalsamplecode/domain/store/service/StoreService.java
> +                ground,
반영 완료

2024-10-28 08:56 UTC, HyunKook-Park commented on src/test/java/com/wearei/finalsamplecode/domain/store/service/StoreServiceTest.java
> +    @Test
반영 완료

2024-10-28 08:57 UTC, jeunwoosung approved these changes

2024-10-28 08:57 UTC, leejaehee0807 approved these changes

2024-10-28 08:58 UTC, duduio2050 approved these changes

2024-10-28 08:58 UTC, merged

2024-11-02 12:23 UTC, minahshin commented on src/test/java/com/wearei/finalsamplecode/domain/store/service/StoreServiceTest.java
> +@SpringBootTest
통합테스트인데 transactional 어노테이션을 달아 rollback 시키지 않는 이유가 있을까요?

2024-11-02 12:23 UTC, minahshin commented on src/test/java/com/wearei/finalsamplecode/domain/store/service/StoreServiceTest.java
> +        teamRepository.save(team);
id값이 auto_increment 속성인 경우에는 transactional 안에서 save로부터 리턴된 객체를 쓰는 것이 constraints 위배(무결성 위배)에 걸리지 않습니다.